version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get install python3-pip
            sudo python3 -m pip install awscli

      - run:
          name: Installing Dependencies
          command: npm install --frozen-lockfile

      - run:
          name: Building
          command: |
            npm run gulp build -- --prod

      - run:
          name: Deploying
          command: |
            aws s3 sync . s3://squeezoid.com --delete --exclude "*" --exclude ".*" --include "*html.gz" --include "privacy-policy/*" --content-encoding gzip --cache-control public,max-age=300 --acl public-read
            aws s3 sync . s3://squeezoid.com --delete --exclude "*" --exclude ".*" --include "font/*" --include "img/*" --include "video/*" --include "sitemap.xml" --cache-control public,max-age=30672000 --acl public-read
