version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Installation of additional packages
          command: |
            sudo apt-get install python python-pip
            sudo pip install awscli

      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile

      - run:
          name: Assembly process
          command: |
            npm run gulp build -- --prod

      - run:
          name: Deploy project
          command: |
            aws s3 sync . s3://squeezoid.com --delete --exclude "*" --exclude ".*" --include "*html" --include "font/*" --include "img/*" --include "video/*" --content-encoding gzip --cache-control public,max-age=30672000
